#!/bin/bash
if [ $# != 3 ]; then
    echo "Usage: `basename $0` <git-repo> <path/to/workdir> <path/to/logdir>"
    exit 0
fi
repo=$1
target="$2"
checkout="$target/checkout"
date_str=$(date +%Y-%m-%d-%H%M%S)
echo "--- run install $date_str ---"
echo "Repo: $repo "
echo "checkout: $checkout"

need_update=false
mkdir -p "$target"
if [ -e "$target/current_run" ]; then
 echo "last update was not successful."
 need_update=true
fi
touch "$target/current_run"
if [ ! -e "$checkout" ]; then
  echo "no target found. Clone $repo to $checkout"
  git clone "$repo" "$checkout"
  need_update=true
  cd $checkout
  echo "repo checkout for the first time."
else
  cd $checkout
  hash=$(git rev-parse HEAD)
  git pull
  new_hash=$(git rev-parse HEAD)
  if [ "$hash" != "$new_hash" ]; then
    echo "repo has been changed."
    need_update=true
  fi
fi

if [ "$need_update" = true ] ;then
  echo "--- run update ..."
  bash ./update.sh   2>&1
  if  [ $? -eq 0 ] ; then
    rm "$target/current_run"
    echo "update successful."
  else
    >&2 echo "update ends with errors: see $log_file"
  fi
fi
echo "install finished. need_update: $need_update "

